### ISSUE TITLE
cannot configure executor for IdleManager

### ISSUE THREAD

**Issue by maxandersen** [oblac/jodd-mail#12]
in java/jakarta mail you can set: `property("mail.event.executor", executor);` to an instance of javax.concurrent.Executor.

In jodd-mail it is only possible to set a string value which is unfortunate.

See https://javaee.github.io/javamail/docs/api/

**Comment by igr** [comment]
Huh, many other properties are deprecated too. There is no `mail.protocol.auth` for example...
That has a major impact on the code, I am afraid.

**Comment by igr** [comment]
Hum or these properties are coming from the implementation, and they will be used at the end...

**Comment by igr** [comment]
Yeah, angus has them: https://github.com/eclipse-ee4j/angus-mail/blob/master/providers/smtp/src/main/java/org/eclipse/angus/mail/smtp/package-info.java

**Comment by igr** [comment]
Added an overloaded method - thank you!
