### ISSUE TITLE
Expose default ports to public (or check port for SSL port)

### ISSUE THREAD

**Issue by ShadowCreator250** [oblac/jodd-mail#18]
Hey! I'm currently trying out this lib and came upon a scenario: 
If the user configures the `ImapServer` with port 993 (default IMAP over SSL port) port but forgets to turn on SSL, then the `MailServer.Builder` will build a normal `ImapServer` instead of a `ImapSslServer`. 

I'm implementing the logic so that SSL is turned on, when the default port is detected. For that, it would be really great if the default port constants were accessible for that. Currently, they are declared as `protected`.

**Comment by igr** [comment]
Make sense, added public to the all ports. Let me know if this helps. I will release tomorrow, of this is ok with you?
