### ISSUE TITLE
Cannot access Address class file for javax.mail.Address not found

### ISSUE THREAD

**Issue by Smarpit-Singh** [oblac/jodd-mail#2]
### The dependency i use
` implementation 'org.jodd:jodd-mail:6.0.1'`

### The code is use  
      
          Email email = Email.create().from(getString(R.string.sender_email))
                .to("-----------")
                .subject("--------")
                .textMessage("----------");

        SmtpServer smtpServer = MailServer.create()
                .ssl(true)
                .host("smtp.gmail.com")
                .auth( "--------------", "----------------------")
                .buildSmtpMailServer();
        SendMailSession session = smtpServer.createSession();

        try {
                 session.open();
                 session.sendMail(email);

        }catch (Exception e){
            e.printStackTrace();
        }
        finally {

            session.close();

        }

### Error Message
![e](https://user-images.githubusercontent.com/27909804/95819879-9691b200-0d44-11eb-9f1c-2061dde8e316.png)

**Comment by igr** [comment]
Please add:

```
	implementation 'jakarta.mail:jakarta.mail-api:1.6.5'
	implementation 'com.sun.mail:jakarta.mail:1.6.5'
```

I will fix this so you don't have to include it by yourself.

**Comment by igr** [comment]
Fixed with `6.0.2`.

**Comment by Smarpit-Singh** [comment]
### I use the latest dependency 6.0.2
`implementation 'org.jodd:jodd-mail:6.0.2'`

### It gave me this error
![e](https://user-images.githubusercontent.com/27909804/95947441-3e25e780-0e0c-11eb-91bc-21c67cf35823.png)

**Comment by igr** [comment]
Sorry, now its resolved in 6.0.3

But you need to add your own IMPL for javax mail.

**Comment by igr** [comment]
See: https://app.gitbook.com/@oblac/s/mail/installation

**Comment by igr** [comment]
see: https://mail.jodd.org/installation
