### ISSUE TITLE
plans for updating to new jakarta package named javamail?

### ISSUE THREAD

**Issue by maxandersen** [oblac/jodd-mail#8]
just curious.

**Comment by igr** [comment]
Sure! I will need to bump the major version as well :)

**Comment by igr** [comment]
Started with migration...

**Comment by igr** [comment]
Tests are green.
However, still need to check if properties like `javax.net.ssl.SSLSocketFactory` have been renamed

**Comment by maxandersen** [comment]
pretty sure that javax.net have not as it is part of JDK not Jakarta.

**Comment by igr** [comment]
The Angus implementation does not support java8 any more, but I guess that is ok :)

**Comment by maxandersen** [comment]
awesome! yeah - java 11 is sufficient these days :)

**Comment by ganomi** [comment]
@igr Do you have a release planned for this or could you create one?
Thank you!

**Comment by igr** [comment]
As soon as we close the #13 !
